keys:
  - &primary age1s8np5jv030y9kdsuwcgrn0rr3sfkm22etdt0q4eqga6cra9x4ems5u9s3m
creation_rules:
  - path_regex: secrets/secrets.yaml$ 
    encrypted_regex: ^(data|ssh_keys)$
    key_groups:
      - age:
        - *primary
